version: "3.9"
services:
  bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    volumes:
      - redis-data:/data
volumes:
  redis-data:
