### FILE: wordbank.py
"""Static word bank for SozMaster AI."""
WORD_BANK = [
    {"word": "achieve", "pronunciation": "/əˈtʃiːv/", "translation_uz": "erishmoq", "example": "You can achieve your goals if you try.", "exercise": "You can _____ your goals if you try."},
    {"word": "enjoy", "pronunciation": "/ɪnˈdʒɔɪ/", "translation_uz": "zavqlanmoq", "example": "We enjoy learning new words every day.", "exercise": "We _____ learning new words every day."},
    {"word": "learn", "pronunciation": "/lɜːrn/", "translation_uz": "o'rganmoq", "example": "Children learn quickly when lessons are fun.", "exercise": "Children _____ quickly when lessons are fun."},
    {"word": "help", "pronunciation": "/hɛlp/", "translation_uz": "yordam bermoq", "example": "Please help your friend with the homework.", "exercise": "Please _____ your friend with the homework."},
    {"word": "create", "pronunciation": "/kriˈeɪt/", "translation_uz": "yaratmoq", "example": "Artists create beautiful pictures with simple tools.", "exercise": "Artists _____ beautiful pictures with simple tools."},
    {"word": "study", "pronunciation": "/ˈstʌdi/", "translation_uz": "o'qimoq", "example": "I study English words every evening.", "exercise": "I _____ English words every evening."},
    {"word": "visit", "pronunciation": "/ˈvɪzɪt/", "translation_uz": "tashrif buyurmoq", "example": "They visit their grandparents every weekend.", "exercise": "They _____ their grandparents every weekend."},
    {"word": "travel", "pronunciation": "/ˈtrævəl/", "translation_uz": "sayohat qilmoq", "example": "We travel to new cities to practice English.", "exercise": "We _____ to new cities to practice English."},
    {"word": "buy", "pronunciation": "/baɪ/", "translation_uz": "sotib olmoq", "example": "She will buy fresh fruit from the market.", "exercise": "She will _____ fresh fruit from the market."},
    {"word": "sell", "pronunciation": "/sɛl/", "translation_uz": "sotmoq", "example": "The farmers sell fresh vegetables at the market.", "exercise": "The farmers _____ fresh vegetables at the market."},
    {"word": "teach", "pronunciation": "/tiːtʃ/", "translation_uz": "o'rgatmoq", "example": "Good mentors teach with patience and care.", "exercise": "Good mentors _____ with patience and care."},
    {"word": "listen", "pronunciation": "/ˈlɪsən/", "translation_uz": "tinglamoq", "example": "Please listen to the new word carefully.", "exercise": "Please _____ to the new word carefully."},
    {"word": "speak", "pronunciation": "/spiːk/", "translation_uz": "gapirmoq", "example": "Try to speak English with your friends.", "exercise": "Try to _____ English with your friends."},
    {"word": "read", "pronunciation": "/riːd/", "translation_uz": "o'qib chiqmoq", "example": "I read short stories before bed.", "exercise": "I _____ short stories before bed."},
    {"word": "write", "pronunciation": "/raɪt/", "translation_uz": "yozmoq", "example": "Students write the new words in a notebook.", "exercise": "Students _____ the new words in a notebook."},
    {"word": "cook", "pronunciation": "/kʊk/", "translation_uz": "pishirmoq", "example": "My mother loves to cook delicious soup for dinner.", "exercise": "My mother loves to _____ delicious soup for dinner."},
    {"word": "clean", "pronunciation": "/kliːn/", "translation_uz": "tozalamoq", "example": "We clean the room before guests arrive.", "exercise": "We _____ the room before guests arrive."},
    {"word": "play", "pronunciation": "/pleɪ/", "translation_uz": "o'ynamoq", "example": "The children play football in the yard.", "exercise": "The children _____ football in the yard."},
    {"word": "work", "pronunciation": "/wɜːrk/", "translation_uz": "ishlamoq", "example": "He must work hard to support his family.", "exercise": "He must _____ hard to support his family."},
    {"word": "relax", "pronunciation": "/rɪˈlæks/", "translation_uz": "dam olmoq", "example": "Take a break and relax for a few minutes.", "exercise": "Take a break and _____ for a few minutes."},
    {"word": "smile", "pronunciation": "/smaɪl/", "translation_uz": "tabassum qilmoq", "example": "Remember to smile when you greet people.", "exercise": "Remember to _____ when you greet people."},
    {"word": "laugh", "pronunciation": "/læf/", "translation_uz": "kulmoq", "example": "They laugh at the funny cartoon.", "exercise": "They _____ at the funny cartoon."},
    {"word": "watch", "pronunciation": "/wɒtʃ/", "translation_uz": "tomosha qilmoq", "example": "We watch English movies with subtitles.", "exercise": "We _____ English movies with subtitles."},
    {"word": "build", "pronunciation": "/bɪld/", "translation_uz": "qurmoq", "example": "Workers build new houses near the park.", "exercise": "Workers _____ new houses near the park."},
    {"word": "drive", "pronunciation": "/draɪv/", "translation_uz": "haydamoq", "example": "My brother can drive carefully at night.", "exercise": "My brother can _____ carefully at night."},
    {"word": "walk", "pronunciation": "/wɔːk/", "translation_uz": "yurmoq", "example": "Let's walk to the bus stop together.", "exercise": "Let's _____ to the bus stop together."},
    {"word": "run", "pronunciation": "/rʌn/", "translation_uz": "yugurmoq", "example": "Athletes run every morning to stay fit.", "exercise": "Athletes _____ every morning to stay fit."},
    {"word": "jump", "pronunciation": "/dʒʌmp/", "translation_uz": "sakramoq", "example": "The kids jump over the small puddles.", "exercise": "The kids _____ over the small puddles."},
    {"word": "sleep", "pronunciation": "/sliːp/", "translation_uz": "uxlamoq", "example": "Babies sleep many hours each day.", "exercise": "Babies _____ many hours each day."},
    {"word": "wake", "pronunciation": "/weɪk/", "translation_uz": "uyg'onmoq", "example": "I wake up early to study quietly.", "exercise": "I _____ up early to study quietly."},
    {"word": "drink", "pronunciation": "/drɪŋk/", "translation_uz": "ichmoq", "example": "Please drink enough water during the day.", "exercise": "Please _____ enough water during the day."},
    {"word": "eat", "pronunciation": "/iːt/", "translation_uz": "yemoq", "example": "We eat dinner together every evening.", "exercise": "We _____ dinner together every evening."},
    {"word": "open", "pronunciation": "/ˈoʊpən/", "translation_uz": "ochmoq", "example": "Can you open the window for fresh air?", "exercise": "Can you _____ the window for fresh air?"},
    {"word": "close", "pronunciation": "/kloʊz/", "translation_uz": "yopmoq", "example": "Please close the door softly.", "exercise": "Please _____ the door softly."},
    {"word": "start", "pronunciation": "/stɑːrt/", "translation_uz": "boshlamoq", "example": "Let's start the lesson with a warm-up.", "exercise": "Let's _____ the lesson with a warm-up."},
    {"word": "finish", "pronunciation": "/ˈfɪnɪʃ/", "translation_uz": "tugatmoq", "example": "We finish our homework before dinner.", "exercise": "We _____ our homework before dinner."},
    {"word": "plan", "pronunciation": "/plæn/", "translation_uz": "rejalashtirmoq", "example": "They plan their week on Sunday night.", "exercise": "They _____ their week on Sunday night."},
    {"word": "organize", "pronunciation": "/ˈɔːrɡənaɪz/", "translation_uz": "tartibga solmoq", "example": "She likes to organize her desk to find things easily.", "exercise": "She likes to _____ her desk to find things easily."},
    {"word": "answer", "pronunciation": "/ˈænsər/", "translation_uz": "javob bermoq", "example": "Please answer the question politely.", "exercise": "Please _____ the question politely."},
    {"word": "ask", "pronunciation": "/æsk/", "translation_uz": "so'ramoq", "example": "Feel free to ask when you need help.", "exercise": "Feel free to _____ when you need help."},
    {"word": "remember", "pronunciation": "/rɪˈmɛmbər/", "translation_uz": "eslamoq", "example": "I remember the new word because of the story.", "exercise": "I _____ the new word because of the story."},
    {"word": "forget", "pronunciation": "/fərˈɡɛt/", "translation_uz": "unutmoq", "example": "Don't forget to review your notes.", "exercise": "Don't _____ to review your notes."},
    {"word": "wait", "pronunciation": "/weɪt/", "translation_uz": "kutmoq", "example": "We wait for the bus under the tree.", "exercise": "We _____ for the bus under the tree."},
    {"word": "send", "pronunciation": "/sɛnd/", "translation_uz": "yubormoq", "example": "I will send you the new vocabulary list.", "exercise": "I will _____ you the new vocabulary list."},
    {"word": "receive", "pronunciation": "/rɪˈsiːv/", "translation_uz": "qabul qilmoq", "example": "Did you receive the message from the teacher?", "exercise": "Did you _____ the message from the teacher?"},
    {"word": "bring", "pronunciation": "/brɪŋ/", "translation_uz": "olib kelmoq", "example": "Please bring your dictionary tomorrow.", "exercise": "Please _____ your dictionary tomorrow."},
    {"word": "take", "pronunciation": "/teɪk/", "translation_uz": "olib ketmoq", "example": "Please take this umbrella because it may rain.", "exercise": "Please _____ this umbrella because it may rain."},
    {"word": "give", "pronunciation": "/ɡɪv/", "translation_uz": "bermoq", "example": "Please give your seat to the elderly person.", "exercise": "Please _____ your seat to the elderly person."},
    {"word": "love", "pronunciation": "/lʌv/", "translation_uz": "sevmoq", "example": "They love spending time together.", "exercise": "They _____ spending time together."},
    {"word": "like", "pronunciation": "/laɪk/", "translation_uz": "yoqtirmoq", "example": "I like this simple explanation.", "exercise": "I _____ this simple explanation."},
    {"word": "need", "pronunciation": "/niːd/", "translation_uz": "kerak bo'lmoq", "example": "You need more practice with pronunciation.", "exercise": "You _____ more practice with pronunciation."},
    {"word": "want", "pronunciation": "/wɑːnt/", "translation_uz": "xohlamoq", "example": "I want to improve my speaking skills.", "exercise": "I _____ to improve my speaking skills."},
    {"word": "choose", "pronunciation": "/tʃuːz/", "translation_uz": "tanlamoq", "example": "Please choose the correct answer from the list.", "exercise": "Please _____ the correct answer from the list."},
    {"word": "change", "pronunciation": "/tʃeɪndʒ/", "translation_uz": "o'zgartirmoq", "example": "We change our plan when it rains.", "exercise": "We _____ our plan when it rains."},
    {"word": "improve", "pronunciation": "/ɪmˈpruːv/", "translation_uz": "yaxshilamoq", "example": "Daily practice helps improve your memory.", "exercise": "Daily practice helps _____ your memory."},
    {"word": "try", "pronunciation": "/traɪ/", "translation_uz": "urinmoq", "example": "Please try to use the new word in a sentence.", "exercise": "Please _____ to use the new word in a sentence."},
    {"word": "use", "pronunciation": "/juːz/", "translation_uz": "ishlatmoq", "example": "You can use this app to remember vocabulary.", "exercise": "You can _____ this app to remember vocabulary."},
    {"word": "share", "pronunciation": "/ʃɛər/", "translation_uz": "bo'lishmoq", "example": "Let's share ideas after the lesson.", "exercise": "Let's _____ ideas after the lesson."},
    {"word": "move", "pronunciation": "/muːv/", "translation_uz": "ko'chmoq", "example": "We move to a new apartment next month.", "exercise": "We _____ to a new apartment next month."},
    {"word": "stay", "pronunciation": "/steɪ/", "translation_uz": "qolmoq", "example": "Please stay calm during the quiz.", "exercise": "Please _____ calm during the quiz."},
    {"word": "meet", "pronunciation": "/miːt/", "translation_uz": "uchrashmoq", "example": "We meet every Friday for conversation club.", "exercise": "We _____ every Friday for conversation club."},
    {"word": "call", "pronunciation": "/kɔːl/", "translation_uz": "qo'ng'iroq qilmoq", "example": "Please call me if you have any questions.", "exercise": "Please _____ me if you have any questions."},
    {"word": "hope", "pronunciation": "/hoʊp/", "translation_uz": "umid qilmoq", "example": "I hope you enjoy today's lesson.", "exercise": "I _____ you enjoy today's lesson."},
    {"word": "worry", "pronunciation": "/ˈwʌri/", "translation_uz": "xavotirlanmoq", "example": "Don't worry about small mistakes.", "exercise": "Don't _____ about small mistakes."},
    {"word": "decide", "pronunciation": "/dɪˈsaɪd/", "translation_uz": "qaror qilmoq", "example": "We decide together which movie to watch.", "exercise": "We _____ together which movie to watch."},
    {"word": "arrive", "pronunciation": "/əˈraɪv/", "translation_uz": "yetib kelmoq", "example": "They arrive at school before eight o'clock.", "exercise": "They _____ at school before eight o'clock."},
    {"word": "leave", "pronunciation": "/liːv/", "translation_uz": "ketmoq", "example": "We leave the office at six in the evening.", "exercise": "We _____ the office at six in the evening."},
    {"word": "believe", "pronunciation": "/bɪˈliːv/", "translation_uz": "ishonmoq", "example": "I believe you can reach your goals.", "exercise": "I _____ you can reach your goals."},
    {"word": "understand", "pronunciation": "/ˌʌndərˈstænd/", "translation_uz": "tushunmoq", "example": "Do you understand the teacher's question?", "exercise": "Do you _____ the teacher's question?"},
    {"word": "explain", "pronunciation": "/ɪkˈspleɪn/", "translation_uz": "tushuntirmoq", "example": "Can you explain the meaning again?", "exercise": "Can you _____ the meaning again?"},
    {"word": "practice", "pronunciation": "/ˈpræktɪs/", "translation_uz": "mashq qilmoq", "example": "We practice speaking for ten minutes daily.", "exercise": "We _____ speaking for ten minutes daily."},
    {"word": "prepare", "pronunciation": "/prɪˈpɛər/", "translation_uz": "tayyorlamoq", "example": "Please prepare your notes before the test.", "exercise": "Please _____ your notes before the test."},
    {"word": "celebrate", "pronunciation": "/ˈsɛləˌbreɪt/", "translation_uz": "nishonlamoq", "example": "We celebrate small victories with friends.", "exercise": "We _____ small victories with friends."},
    {"word": "discover", "pronunciation": "/dɪˈskʌvər/", "translation_uz": "kashf etmoq", "example": "They discover new cafes in the city.", "exercise": "They _____ new cafes in the city."},
    {"word": "protect", "pronunciation": "/prəˈtɛkt/", "translation_uz": "himoya qilmoq", "example": "Wear a hat to protect your head from the sun.", "exercise": "Wear a hat to _____ your head from the sun."},
    {"word": "support", "pronunciation": "/səˈpɔːrt/", "translation_uz": "qo'llab-quvvatlamoq", "example": "Good friends support each other in hard times.", "exercise": "Good friends _____ each other in hard times."},
    {"word": "agree", "pronunciation": "/əˈɡriː/", "translation_uz": "rozi bo'lmoq", "example": "I agree with your smart idea.", "exercise": "I _____ with your smart idea."},
    {"word": "disagree", "pronunciation": "/ˌdɪsəˈɡriː/", "translation_uz": "rozi bo'lmaslik", "example": "It's okay to disagree politely.", "exercise": "It's okay to _____ politely."},
    {"word": "borrow", "pronunciation": "/ˈbɒroʊ/", "translation_uz": "qarzga olmoq", "example": "May I borrow your dictionary for a moment?", "exercise": "May I _____ your dictionary for a moment?"},
    {"word": "lend", "pronunciation": "/lɛnd/", "translation_uz": "qarzga bermoq", "example": "I can lend you my notes.", "exercise": "I can _____ you my notes."},
    {"word": "save", "pronunciation": "/seɪv/", "translation_uz": "tejamoq", "example": "Please save your money for the trip.", "exercise": "Please _____ your money for the trip."},
    {"word": "spend", "pronunciation": "/spɛnd/", "translation_uz": "sarflamoq", "example": "We spend our weekends with family.", "exercise": "We _____ our weekends with family."},
    {"word": "pay", "pronunciation": "/peɪ/", "translation_uz": "to'lamoq", "example": "He will pay the bill after dinner.", "exercise": "He will _____ the bill after dinner."},
    {"word": "cost", "pronunciation": "/kɒst/", "translation_uz": "narxi bo'lmoq", "example": "How much does this notebook cost?", "exercise": "How much does this notebook _____?"},
    {"word": "imagine", "pronunciation": "/ɪˈmædʒən/", "translation_uz": "tasavvur qilmoq", "example": "Please imagine the story while you listen.", "exercise": "Please _____ the story while you listen."},
    {"word": "draw", "pronunciation": "/drɔː/", "translation_uz": "chizmoq", "example": "She loves to draw simple sketches.", "exercise": "She loves to _____ simple sketches."},
    {"word": "paint", "pronunciation": "/peɪnt/", "translation_uz": "bo'yamoq", "example": "They paint the walls a bright color.", "exercise": "They _____ the walls a bright color."},
    {"word": "sing", "pronunciation": "/sɪŋ/", "translation_uz": "kuylamoq", "example": "We sing along to English songs.", "exercise": "We _____ along to English songs."},
    {"word": "dance", "pronunciation": "/dæns/", "translation_uz": "raqsga tushmoq", "example": "They dance happily at the party.", "exercise": "They _____ happily at the party."},
    {"word": "swim", "pronunciation": "/swɪm/", "translation_uz": "suzmoq", "example": "We swim in the pool during summer.", "exercise": "We _____ in the pool during summer."},
    {"word": "climb", "pronunciation": "/klaɪm/", "translation_uz": "tirmashmoq", "example": "Hikers climb the hill slowly.", "exercise": "Hikers _____ the hill slowly."},
    {"word": "plant", "pronunciation": "/plænt/", "translation_uz": "ekmoq", "example": "Let's plant flowers in the garden.", "exercise": "Let's _____ flowers in the garden."},
    {"word": "water", "pronunciation": "/ˈwɔːtər/", "translation_uz": "sug'ormoq", "example": "Remember to water the plants daily.", "exercise": "Remember to _____ the plants daily."},
    {"word": "grow", "pronunciation": "/ɡroʊ/", "translation_uz": "o'smoq", "example": "Children grow fast when they eat well.", "exercise": "Children _____ fast when they eat well."},
    {"word": "harvest", "pronunciation": "/ˈhɑːrvɪst/", "translation_uz": "hosil yig'moq", "example": "Farmers harvest the wheat in autumn.", "exercise": "Farmers _____ the wheat in autumn."},
    {"word": "repair", "pronunciation": "/rɪˈpɛər/", "translation_uz": "ta'mirlamoq", "example": "He can repair the broken chair.", "exercise": "He can _____ the broken chair."},
    {"word": "fix", "pronunciation": "/fɪks/", "translation_uz": "tuzatmoq", "example": "Please fix the loose button on your shirt.", "exercise": "Please _____ the loose button on your shirt."},
    {"word": "deliver", "pronunciation": "/dɪˈlɪvər/", "translation_uz": "yetkazib bermoq", "example": "The courier will deliver the package today.", "exercise": "The courier will _____ the package today."},
    {"word": "collect", "pronunciation": "/kəˈlɛkt/", "translation_uz": "to'plamoq", "example": "We collect new phrases in our notebook.", "exercise": "We _____ new phrases in our notebook."},
    {"word": "guide", "pronunciation": "/ɡaɪd/", "translation_uz": "yo'l ko'rsatmoq", "example": "The mentor will guide you through the lesson.", "exercise": "The mentor will _____ you through the lesson."},
]
